version: "3"
services:
  springBootApp:
    image: paakhi/project-demo:1.0
    container_name: docker-postgres-springboot-demo-app
    environment:
      - POSTGRES_HOST=docker-postgres-springboot-db
      - SERVER_PORT=9056
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDb:5432/dbexample1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Krpy@10271611
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9008:9056"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure

  postgresDb:
    image: postgres:13.2
    container_name: docker-postgres-springboot-demo-db
    ports:
      - "5434:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Krpy@10271611
      - POSTGRES_DB=dbexample1
networks:
 network:
volumes:
 volume: